//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// Der Quellcode wurde automatisch mit Microsoft.VSDesigner generiert. Version 1.1.4322.2032.
// 
namespace WebServiceTest.railsservice {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SimpleServiceSimpleServiceBinding", Namespace="urn:ActionWebService")]
    public class SimpleServiceServiceWse : Microsoft.Web.Services2.WebServicesClientProtocol {
        
        /// <remarks/>
        public SimpleServiceServiceWse() {
            this.Url = "http://localhost:3000/simple_service/api";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("/simple_service/api/test", RequestNamespace="urn:ActionWebService", ResponseNamespace="urn:ActionWebService")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string test(string param0) {
            object[] results = this.Invoke("test", new object[] {
                        param0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begintest(string param0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("test", new object[] {
                        param0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endtest(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SimpleServiceSimpleServiceBinding", Namespace="urn:ActionWebService")]
    public class SimpleServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public SimpleServiceService() {
            this.Url = "http://localhost:3000/simple_service/api";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("/simple_service/api/test", RequestNamespace="urn:ActionWebService", ResponseNamespace="urn:ActionWebService")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string test(string param0) {
            object[] results = this.Invoke("test", new object[] {
                        param0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begintest(string param0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("test", new object[] {
                        param0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endtest(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
